"""
HLAF methods generated by the o3-based Sb-A, Pb-A, and Co-A agents.

Example:
    hlafs = GeneratedHLAFs({
        "Robot_1": robot_1_controller,
        "Robot_2": robot_2_controller,
    })
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from typing import Any, Mapping

import numpy as np


HLAF_MANIFEST = [
  {
    "index": 1,
    "function": "hlaf_001_vertical_stud_set_stud_on_bottom_plate_layout_mark_and_tip_into_place_under",
    "element": "Vertical Stud",
    "sub_step": "Set stud on bottom plate layout mark and tip into place under top plate",
    "required_variables": [
      "L",
      "W",
      "H",
      "X"
    ],
    "agents": [
      "Sb-A",
      "Pb-A"
    ],
    "poses": [
      "Vertical_Stud_Pick_Pose",
      "Vertical_Stud_Place_Pose"
    ]
  },
  {
    "index": 2,
    "function": "hlaf_002_vertical_stud_fasten_stud_to_plates_with_nails_or_screws_through_toe_nailing",
    "element": "Vertical Stud",
    "sub_step": "Fasten stud to plates with nails or screws through toe-nailing or metal connectors",
    "required_variables": [
      "H"
    ],
    "agents": [
      "Pb-A"
    ],
    "poses": [
      "Vertical_Stud_Nail_Pose"
    ]
  },
  {
    "index": 3,
    "function": "hlaf_003_king_stud_stand_each_king_stud_against_layout_line_flanking_rough_opening",
    "element": "King Stud",
    "sub_step": "Stand each king stud against layout line flanking rough opening",
    "required_variables": [
      "L",
      "W",
      "H",
      "X"
    ],
    "agents": [
      "Sb-A",
      "Pb-A"
    ],
    "poses": [
      "King_Stud_Pick_Pose",
      "King_Stud_Place_Pose"
    ]
  },
  {
    "index": 4,
    "function": "hlaf_004_king_stud_secure_king_studs_to_bottom_and_top_plates_with_nails_or_structura",
    "element": "King Stud",
    "sub_step": "Secure king studs to bottom and top plates with nails or structural screws",
    "required_variables": [
      "H"
    ],
    "agents": [
      "Pb-A"
    ],
    "poses": [
      "King_Stud_Nail_Pose"
    ]
  },
  {
    "index": 5,
    "function": "hlaf_005_lower_cripple_stud_position_cripples_at_marked_on_center_spacing_below_sill",
    "element": "Lower Cripple Stud",
    "sub_step": "Position cripples at marked on-center spacing below sill opening",
    "required_variables": [
      "L",
      "W",
      "H",
      "X"
    ],
    "agents": [
      "Sb-A",
      "Pb-A"
    ],
    "poses": [
      "Lower_Cripple_Plate_Pick_Pose",
      "Lower_Cripple_Plate_Place_Pose"
    ]
  },
  {
    "index": 6,
    "function": "hlaf_006_osb_sheathing_plate_position_first_sheet_flush_with_bottom_plate_and_edge_of",
    "element": "OSB Sheathing Plate",
    "sub_step": "Position first sheet flush with bottom plate and edge of framing",
    "required_variables": [
      "H",
      "X",
      "Z"
    ],
    "agents": [
      "Sb-A",
      "Pb-A"
    ],
    "poses": [
      "OSB_Sheathing_Plate_Pick_Pose",
      "OSB_Sheathing_Plate_Place_Pose"
    ]
  },
  {
    "index": 7,
    "function": "hlaf_007_osb_sheathing_plate_fasten_osb_to_studs_plates_and_blocking_with_specified_n",
    "element": "OSB Sheathing Plate",
    "sub_step": "Fasten OSB to studs, plates, and blocking with specified nails or screws at required spacing, starting from center and working outward",
    "required_variables": [
      "L",
      "H"
    ],
    "agents": [
      "Pb-A"
    ],
    "poses": [
      "OSB_Sheathing_Plate_Nail_Pose"
    ]
  },
  {
    "index": 8,
    "function": "hlaf_008_top_plate_install_second_cap_plate_overlapping_joints_for_strength",
    "element": "Top Plate",
    "sub_step": "Install second (cap) plate overlapping joints for strength",
    "required_variables": [
      "L",
      "W",
      "H",
      "X"
    ],
    "agents": [
      "Sb-A",
      "Co-A",
      "Co-A",
      "Pb-A"
    ],
    "poses": [
      "Top_Plate_Pick_Pose",
      "Top_Plate_Pass_Pose",
      "Top_Plate_Pass_Pose",
      "Top_Plate_Place_Pose"
    ]
  },
  {
    "index": 9,
    "function": "hlaf_009_jack_stud_place_each_jack_stud_against_king_stud_at_opening_sides",
    "element": "Jack Stud",
    "sub_step": "Place each jack stud against king stud at opening sides",
    "required_variables": [
      "L",
      "W",
      "H",
      "X"
    ],
    "agents": [
      "Sb-A",
      "Pb-A"
    ],
    "poses": [
      "Jack_Stud_Pick_Pose",
      "Jack_Stud_Place_Pose"
    ]
  },
  {
    "index": 10,
    "function": "hlaf_010_jack_stud_nail_jack_studs_to_king_studs_and_bottom_plate_then_toenail_into_h",
    "element": "Jack Stud",
    "sub_step": "Nail jack studs to king studs and bottom plate, then toenail into header after placement",
    "required_variables": [
      "L",
      "X"
    ],
    "agents": [
      "Pb-A"
    ],
    "poses": [
      "Jack_Stud_Nail_Pose"
    ]
  },
  {
    "index": 11,
    "function": "hlaf_011_bear_loading_lift_header_onto_jack_studs_within_opening_using_additional_hel",
    "element": "Bear Loading",
    "sub_step": "Lift header onto jack studs within opening using additional help or temporary support",
    "required_variables": [
      "W",
      "X"
    ],
    "agents": [
      "Sb-A",
      "Pb-A"
    ],
    "poses": [
      "Load_Bearing_Pick_Pose",
      "Load_Bearing_Place_Pose"
    ]
  },
  {
    "index": 12,
    "function": "hlaf_012_bear_loading_nail_or_screw_header_to_jack_studs_and_add_metal_hangers_or_str",
    "element": "Bear Loading",
    "sub_step": "Nail or screw header to jack studs and add metal hangers or straps if required",
    "required_variables": [
      "W",
      "H",
      "X",
      "Z"
    ],
    "agents": [
      "Pb-A"
    ],
    "poses": [
      "Load_Bearing_Nail_Pose"
    ]
  },
  {
    "index": 13,
    "function": "hlaf_013_l_u_stud_stand_stud_in_place_providing_space_for_service_penetrations_as_det",
    "element": "L/U Stud",
    "sub_step": "Stand stud in place providing space for service penetrations as detailed",
    "required_variables": [
      "L",
      "W",
      "H",
      "X",
      "Z"
    ],
    "agents": [
      "Sb-A",
      "Co-A",
      "Co-A",
      "Pb-A"
    ],
    "poses": [
      "L_U_Stud_Pick_Pose",
      "L_U_Stud_Pass_Pose",
      "L_U_Stud_Pass_Pose",
      "L_U_Stud_Place_Pose"
    ]
  },
  {
    "index": 14,
    "function": "hlaf_014_lower_sill_plate_position_sill_on_marked_lines_with_crown_up_and_faces_flush",
    "element": "Lower Sill Plate",
    "sub_step": "Position sill on marked lines with crown up and faces flush",
    "required_variables": [
      "W",
      "H",
      "X"
    ],
    "agents": [
      "Sb-A",
      "Pb-A"
    ],
    "poses": [
      "Lower_Sill_Plate_Pick_Pose",
      "Lower_Sill_Plate_Place_Pose"
    ]
  },
  {
    "index": 15,
    "function": "hlaf_015_lower_sill_plate_tack_sill_to_king_or_jack_studs_then_secure_with_nails_or_s",
    "element": "Lower Sill Plate",
    "sub_step": "Tack sill to king or jack studs, then secure with nails or screws through end joints",
    "required_variables": [
      "W",
      "H",
      "X"
    ],
    "agents": [
      "Pb-A"
    ],
    "poses": [
      "Lower_Sill_Plate_Nail_Pose"
    ]
  },
  {
    "index": 16,
    "function": "hlaf_016_bottom_plate_fasten_plate_to_floor_framing_or_slab_with_nails_screws_or_anch",
    "element": "Bottom Plate",
    "sub_step": "Fasten plate to floor framing or slab with nails, screws, or anchors per specification",
    "required_variables": [
      "H"
    ],
    "agents": [
      "Pb-A"
    ],
    "poses": [
      "Bottom_Plate_Nail_Pose"
    ]
  },
  {
    "index": 17,
    "function": "hlaf_017_top_sill_plate_set_top_sill_on_marks_and_hold_flush_with_inner_faces_of_stud",
    "element": "Top Sill Plate",
    "sub_step": "Set top sill on marks and hold flush with inner faces of studs",
    "required_variables": [
      "W",
      "H",
      "X"
    ],
    "agents": [
      "Sb-A",
      "Co-A",
      "Co-A",
      "Pb-A"
    ],
    "poses": [
      "Top_Sill_Plate_Pick_Pose",
      "Top_Sill_Plate_Pass_Pose",
      "Top_Sill_Plate_Pass_Pose",
      "Top_Sill_Plate_Place_Pose"
    ]
  },
  {
    "index": 18,
    "function": "hlaf_018_top_sill_plate_nail_or_screw_plate_to_king_studs_and_to_any_top_cripple_stud",
    "element": "Top Sill Plate",
    "sub_step": "Nail or screw plate to king studs and to any top cripple studs above",
    "required_variables": [
      "W",
      "H",
      "X"
    ],
    "agents": [
      "Pb-A"
    ],
    "poses": [
      "Top_Sill_Plate_Nail_Pose"
    ]
  },
  {
    "index": 19,
    "function": "hlaf_019_top_cripple_stud_position_cripples_at_on_center_spacing_above_opening_betwee",
    "element": "Top Cripple Stud",
    "sub_step": "Position cripples at on-center spacing above opening between header and top plate",
    "required_variables": [
      "L",
      "W",
      "H",
      "X"
    ],
    "agents": [
      "Sb-A",
      "Co-A",
      "Co-A",
      "Pb-A"
    ],
    "poses": [
      "Top_Cripple_Plate_Pick_Pose",
      "Top_Cripple_Plate_Pass_Pose",
      "Top_Cripple_Plate_Pass_Pose",
      "Top_Cripple_Plate_Place_Pose"
    ]
  },
  {
    "index": 20,
    "function": "hlaf_020_top_cripple_stud_fasten_cripples_through_top_plate_and_header_with_nails_or",
    "element": "Top Cripple Stud",
    "sub_step": "Fasten cripples through top plate and header with nails or screws",
    "required_variables": [
      "H"
    ],
    "agents": [
      "Pb-A"
    ],
    "poses": [
      "Top_Cripple_Plate_Nail_Pose"
    ]
  }
]


class GeneratedHLAFs:
    def __init__(
        self,
        robots: Mapping[str, Any],
    ) -> None:
        self.robots = dict(robots)

    def hlaf_001_vertical_stud_set_stud_on_bottom_plate_layout_mark_and_tip_into_place_under(self, element_object_name: str, *, L: float, W: float, H: float, X: float) -> None:
        """
        Element: Vertical Stud
        Sub-Step: Set stud on bottom plate layout mark and tip into place under top plate
        """
        robot_2 = self.robots["Robot_2"]

        robot_2.plan("tool0", np.array([4.179000, -2.422283 + (0.250000 * W), 1.048050 + (0.433013 * W)], dtype=float), np.array([0.612354, 0.612354, 0.353553, 0.353553], dtype=float))
        robot_2.render_exec()
        robot_2.eef_attach("IRB6620_R2", "tool0", "Vertical Stud")
        robot_2.move_to_home()

        robot_2.plan("tool0", np.array([X + (L / 2) + 0.962590, 0.500000, H + 0.889360], dtype=float), np.array([0.0, 0.0, 0.707107, 0.707107], dtype=float))
        robot_2.render_exec()
        robot_2.eef_detach("IRB6620_R2", "tool0", "Vertical Stud")
        robot_2.move_to_home()

    def hlaf_002_vertical_stud_fasten_stud_to_plates_with_nails_or_screws_through_toe_nailing(self, element_object_name: str, *, H: float) -> None:
        """
        Element: Vertical Stud
        Sub-Step: Fasten stud to plates with nails or screws through toe-nailing or metal connectors
        """
        robot_1 = self.robots["Robot_1"]

        robot_1.plan("tool2", np.array([1.100000, 0.500000, 0.895460 + (0.300000 * H)], dtype=float), np.array([0.0, 0.707107, 0.0, 0.707107], dtype=float))
        robot_1.render_exec()
        robot_1.move_to_home()

    def hlaf_003_king_stud_stand_each_king_stud_against_layout_line_flanking_rough_opening(self, element_object_name: str, *, L: float, W: float, H: float, X: float) -> None:
        """
        Element: King Stud
        Sub-Step: Stand each king stud against layout line flanking rough opening
        """
        robot_2 = self.robots["Robot_2"]

        robot_2.plan("tool0", np.array([4.179000, -2.422283 + (0.250000 * W), 1.048050 + (0.433013 * W)], dtype=float), np.array([0.612354, 0.612354, 0.353553, 0.353553], dtype=float))
        robot_2.render_exec()
        robot_2.eef_attach("IRB6620_R2", "tool0", "King Stud")
        robot_2.move_to_home()

        robot_2.plan("Gripper", np.array([X + (L / 2) + 0.962590, 0.500000, H + 0.889360], dtype=float), np.array([0.0, 0.0, 0.707107, 0.707107], dtype=float))
        robot_2.render_exec()
        robot_2.eef_detach("IRB6620_R2", "tool0", "King Stud")
        robot_2.move_to_home()

    def hlaf_004_king_stud_secure_king_studs_to_bottom_and_top_plates_with_nails_or_structura(self, element_object_name: str, *, H: float) -> None:
        """
        Element: King Stud
        Sub-Step: Secure king studs to bottom and top plates with nails or structural screws
        """
        robot_1 = self.robots["Robot_1"]

        robot_1.plan("tool2", np.array([1.100000, 0.500000, 0.895460 + (0.300000 * H)], dtype=float), np.array([0.0, 0.707107, 0.0, 0.707107], dtype=float))
        robot_1.render_exec()
        robot_1.move_to_home()

    def hlaf_005_lower_cripple_stud_position_cripples_at_marked_on_center_spacing_below_sill(self, element_object_name: str, *, L: float, W: float, H: float, X: float) -> None:
        """
        Element: Lower Cripple Stud
        Sub-Step: Position cripples at marked on-center spacing below sill opening
        """
        robot_2 = self.robots["Robot_2"]

        robot_2.plan('tool0', np.array([6.450100, 0.782470, 0.803000 + (W / 2)], dtype=float), np.array([-0.707107, 0.0, -0.707107, 0.0], dtype=float))
        robot_2.render_exec()
        robot_2.eef_attach('IRB6620_R2', 'tool0', 'Lower Cripple Stud')
        robot_2.move_to_home()

        robot_2.plan("tool0", np.array([X - (L / 2) + 1.182590, 0.0, H + 0.889360], dtype=float), np.array([0.0, 0.0, -0.707107, -0.707107], dtype=float))
        robot_2.render_exec()
        robot_2.eef_detach("IRB6620_R2", "tool0", "Lower Cripple Stud")
        robot_2.move_to_home()

    def hlaf_006_osb_sheathing_plate_position_first_sheet_flush_with_bottom_plate_and_edge_of(self, element_object_name: str, *, H: float, X: float, Z: float) -> None:
        """
        Element: OSB Sheathing Plate
        Sub-Step: Position first sheet flush with bottom plate and edge of framing
        """
        robot_1 = self.robots["Robot_1"]

        robot_1.plan('tool1', np.array([0.0, -1.5, H + 0.6], dtype=float), np.array([0.0, 0.0, 0.707107, 0.707107], dtype=float))
        robot_1.render_exec()
        robot_1.eef_attach('IRB6620_R1', 'tool1', 'OSB Sheathing Plate')
        robot_1.move_to_home()

        robot_1.plan('Suction_Cup', np.array([2.691790 - X, 0.0, Z + 0.895460], dtype=float), np.array([0.0, 0.0, 0.0, -1.0], dtype=float))
        robot_1.render_exec(True, True, False)
        robot_1.eef_detach('IRB6620_R1', 'tool1', 'OSB Sheathing Plate')
        robot_1.move_to_home(False, [0, -0.5, 0.5, 0, 0, 0], [])

    def hlaf_007_osb_sheathing_plate_fasten_osb_to_studs_plates_and_blocking_with_specified_n(self, element_object_name: str, *, L: float, H: float) -> None:
        """
        Element: OSB Sheathing Plate
        Sub-Step: Fasten OSB to studs, plates, and blocking with specified nails or screws at required spacing, starting from center and working outward
        """
        robot_1 = self.robots["Robot_1"]

        robot_1.plan("tool2", np.array([L + 1.152590, 0.0, H + 1.047060], dtype=float), np.array([0.0, 1.0, 0.0, 0.0], dtype=float))
        robot_1.render_exec()
        robot_1.move_to_home()

    def hlaf_008_top_plate_install_second_cap_plate_overlapping_joints_for_strength(self, element_object_name: str, *, L: float, W: float, H: float, X: float) -> None:
        """
        Element: Top Plate
        Sub-Step: Install second (cap) plate overlapping joints for strength
        """
        robot_2 = self.robots["Robot_2"]
        robot_1 = self.robots["Robot_1"]

        robot_2.plan("tool0", np.array([6.450100, 1.003400, 0.803000 + (W / 2)], dtype=float), np.array([0.707107, 0.0, 0.707107, 0.0], dtype=float))
        robot_2.render_exec()
        robot_2.eef_attach("IRB6620_R2", "tool0", "Top Plate")
        robot_2.move_to_home()

        robot_2.plan(tcp_name='tool0', target_pose=np.array([2.250000 + (L / 2), -1.000000, H + 0.850000], dtype=float), target_orientation=np.array([0.0, 0.0, 0.707107, 0.707107], dtype=float))
        robot_1.plan(tcp_name='tool0', target_pose=np.array([2.250000 + (L / 2), -1.000000, H + 0.850000], dtype=float), target_orientation=np.array([0.0, 0.0, 0.707107, 0.707107], dtype=float))
        with ThreadPoolExecutor(max_workers=2) as executor:
            giver_exec = executor.submit(
                robot_2.render_exec,
                is_synchronizer=False,
            )
            receiver_exec = executor.submit(
                robot_1.render_exec,
                is_synchronizer=True,
            )
            giver_exec.result()
            receiver_exec.result()
        robot_1.eef_attach('IRB6620_R1', 'Gripper', 'Top Plate')
        robot_2.eef_detach('IRB6620_R2', 'Gripper', 'Top Plate')
        with ThreadPoolExecutor(max_workers=2) as executor:
            giver_home = executor.submit(
                robot_2.move_to_home
            )
            receiver_home = executor.submit(
                robot_1.move_to_home
            )
            giver_home.result()
            receiver_home.result()

        robot_1.plan('tool0', np.array([X + 1.132590, 0.0, H + 0.889360], dtype=float), np.array([0.0, 0.0, 1.0, 0.0], dtype=float))
        robot_1.render_exec()
        robot_1.eef_detach(r_name='IRB6620_R1', tool_name='tool0', detaching_object_name='Top Plate')
        robot_1.move_to_home()

    def hlaf_009_jack_stud_place_each_jack_stud_against_king_stud_at_opening_sides(self, element_object_name: str, *, L: float, W: float, H: float, X: float) -> None:
        """
        Element: Jack Stud
        Sub-Step: Place each jack stud against king stud at opening sides
        """
        robot_2 = self.robots["Robot_2"]

        robot_2.plan("tool0", np.array([6.450100, 0.782470, 0.803000 + (W / 2)], dtype=float), np.array([-0.707107, 0.0, -0.707107, 0.0], dtype=float))
        robot_2.render_exec()
        robot_2.eef_attach("IRB6620_R2", "tool0", "Jack Stud")
        robot_2.move_to_home()

        target_pose = np.array([X + (L / 2) + 1.082590, 0.500000, H + 0.939360], dtype=float)
        target_orientation = np.array([0.0, 0.0, -0.707107, 0.707107], dtype=float)
        robot_2.plan("tool0", target_pose, target_orientation)
        robot_2.render_exec()
        robot_2.eef_detach("IRB6620_R2", "tool0", "Jack Stud")
        robot_2.move_to_home()

    def hlaf_010_jack_stud_nail_jack_studs_to_king_studs_and_bottom_plate_then_toenail_into_h(self, element_object_name: str, *, L: float, X: float) -> None:
        """
        Element: Jack Stud
        Sub-Step: Nail jack studs to king studs and bottom plate, then toenail into header after placement
        """
        robot_1 = self.robots["Robot_1"]

        robot_1.plan("tool2", np.array([X - (L / 2) + 1.193550, 0.586603, 0.945460], dtype=float), np.array([0.353553, -0.612354, 0.612354, 0.353553], dtype=float))
        robot_1.render_exec(renderInstance=True, Show_Sphere=True, is_synchronizer=False)
        robot_1.move_to_home(if_show_spheres=False, Customized_JS=[0, -0.5, 0.5, 0, 0, 0], removing_primitives=[])

    def hlaf_011_bear_loading_lift_header_onto_jack_studs_within_opening_using_additional_hel(self, element_object_name: str, *, W: float, X: float) -> None:
        """
        Element: Bear Loading
        Sub-Step: Lift header onto jack studs within opening using additional help or temporary support
        """
        robot_1 = self.robots["Robot_1"]

        robot_1.plan("tool1", np.array([-1.127, 1.02, 0.354], dtype=float), np.array([0.0, 0.0, 0.707107, -0.707107], dtype=float))
        robot_1.render_exec()
        robot_1.eef_attach("IRB6620_R1", "tool1", "Bear Loading")
        robot_1.move_to_home()

        robot_1.plan("tool1", np.array([X + 1.132590, 0.0, W + 1.045460], dtype=float), np.array([0.0, 0.0, 0.707107, 0.707107], dtype=float))
        robot_1.render_exec()
        robot_1.eef_detach("IRB6620_R1", "tool1", "Bear Loading")
        robot_1.move_to_home()

    def hlaf_012_bear_loading_nail_or_screw_header_to_jack_studs_and_add_metal_hangers_or_str(self, element_object_name: str, *, W: float, H: float, X: float, Z: float) -> None:
        """
        Element: Bear Loading
        Sub-Step: Nail or screw header to jack studs and add metal hangers or straps if required
        """
        robot_1 = self.robots["Robot_1"]

        robot_1.plan("tool2", np.array([X + (0.200000 * H) + 1.132590, 0.429289 - (W / 2), Z + 0.986491], dtype=float), np.array([0.27061, 0.27061, -0.653296, 0.653296], dtype=float))
        robot_1.render_exec()
        robot_1.move_to_home()

    def hlaf_013_l_u_stud_stand_stud_in_place_providing_space_for_service_penetrations_as_det(self, element_object_name: str, *, L: float, W: float, H: float, X: float, Z: float) -> None:
        """
        Element: L/U Stud
        Sub-Step: Stand stud in place providing space for service penetrations as detailed
        """
        robot_2 = self.robots["Robot_2"]
        robot_1 = self.robots["Robot_1"]

        robot_2.plan("tool0", np.array([4.179000, -2.422283 + (0.250000 * W), 1.048050 + (0.433013 * W)], dtype=float), np.array([0.612354, 0.612354, 0.353553, 0.353553], dtype=float))
        robot_2.render_exec()
        robot_2.eef_attach("IRB6620_R2", "tool0", "L/U Stud")
        robot_2.move_to_home()

        robot_2.plan("tool0", np.array([2.816340 - (0.866025), 1.244430 + (H / 2), 1.297380 + (0.500000)], dtype=float), np.array([0.0, 0.96593, 0.0, 0.25882], dtype=float))
        robot_1.plan("tool1", np.array([2.816340 - (0.866025), 1.244430 + (H / 2), 1.297380 + (0.500000)], dtype=float), np.array([0.0, 0.96593, 0.0, 0.25882], dtype=float))
        with ThreadPoolExecutor(max_workers=2) as executor:
            giver_exec = executor.submit(
                robot_2.render_exec,
                is_synchronizer=False,
            )
            receiver_exec = executor.submit(
                robot_1.render_exec,
                is_synchronizer=True,
            )
            giver_exec.result()
            receiver_exec.result()
        robot_1.eef_attach("IRB6620_R1", "Suction_Cup", "L/U Stud")
        robot_2.eef_detach("IRB6620_R2", "Gripper", "L/U Stud")
        with ThreadPoolExecutor(max_workers=2) as executor:
            giver_home = executor.submit(
                robot_2.move_to_home
            )
            receiver_home = executor.submit(
                robot_1.move_to_home
            )
            giver_home.result()
            receiver_home.result()

        robot_1.plan('tool1', np.array([3.650990 - X - (L / 2), 0.0, 0.895460 + Z + (W / 2)], dtype=float), np.array([0.0, 0.0, 1.0, 0.0], dtype=float))
        robot_1.render_exec()
        robot_1.eef_detach('IRB6620_R1', 'tool1', 'L/U Stud')
        robot_1.move_to_home()

    def hlaf_014_lower_sill_plate_position_sill_on_marked_lines_with_crown_up_and_faces_flush(self, element_object_name: str, *, W: float, H: float, X: float) -> None:
        """
        Element: Lower Sill Plate
        Sub-Step: Position sill on marked lines with crown up and faces flush
        """
        robot_2 = self.robots["Robot_2"]

        robot_2.plan("tool0", np.array([6.450100, 0.782470, 0.803000 + (W / 2)], dtype=float), np.array([-0.707107, 0.0, -0.707107, 0.0], dtype=float))
        robot_2.render_exec()
        robot_2.eef_attach("IRB6620_R2", "tool0", "Lower Sill Plate")
        robot_2.move_to_home()

        robot_2.plan(tcp_name="Gripper", target_pose=np.array([X + 1.132590, 0.0, H + 1.189360], dtype=float), target_orientation=np.array([0.0, 0.0, -1.0, 0.0], dtype=float))
        robot_2.render_exec()
        robot_2.eef_detach(r_name="IRB6620_R2", tool_name="tool0", detaching_object_name="Lower Sill Plate")
        robot_2.move_to_home()

    def hlaf_015_lower_sill_plate_tack_sill_to_king_or_jack_studs_then_secure_with_nails_or_s(self, element_object_name: str, *, W: float, H: float, X: float) -> None:
        """
        Element: Lower Sill Plate
        Sub-Step: Tack sill to king or jack studs, then secure with nails or screws through end joints
        """
        robot_2 = self.robots["Robot_2"]

        robot_2.plan("tool1", np.array([X + 1.132590, -0.413397 + (1.500000 * W), 0.945460 + (0.300000 * H)], dtype=float), np.array([0.0, 0.0, 0.353553, 0.612354], dtype=float))
        robot_2.render_exec()
        robot_2.move_to_home()

    def hlaf_016_bottom_plate_fasten_plate_to_floor_framing_or_slab_with_nails_screws_or_anch(self, element_object_name: str, *, H: float) -> None:
        """
        Element: Bottom Plate
        Sub-Step: Fasten plate to floor framing or slab with nails, screws, or anchors per specification
        """
        robot_2 = self.robots["Robot_2"]

        robot_2.plan('tool1', np.array([3.690000, 0, 0.895460 + (0.300000 * H)], dtype=float), np.array([0.0, 0.5, 0.5, 0.5], dtype=float))
        robot_2.render_exec()
        robot_2.move_to_home()

    def hlaf_017_top_sill_plate_set_top_sill_on_marks_and_hold_flush_with_inner_faces_of_stud(self, element_object_name: str, *, W: float, H: float, X: float) -> None:
        """
        Element: Top Sill Plate
        Sub-Step: Set top sill on marks and hold flush with inner faces of studs
        """
        robot_2 = self.robots["Robot_2"]
        robot_1 = self.robots["Robot_1"]

        robot_2.plan('tool0', np.array([6.450100, 0.782470, 0.803000 + (W / 2)], dtype=float), np.array([-0.707107, 0.0, -0.707107, 0.0], dtype=float))
        robot_2.render_exec()
        robot_2.eef_attach('IRB6620_R2', 'tool0', 'Top Sill Plate')
        robot_2.move_to_home()

        robot_2.plan("tool0", np.array([1.762200 - (H / 2), -0.150000, 1.550000], dtype=float), np.array([0.0, 0.707107, 0.0, 0.707107], dtype=float))
        robot_1.plan("tool0", np.array([1.762200 - (H / 2), -0.150000, 1.550000], dtype=float), np.array([0.0, 0.707107, 0.0, 0.707107], dtype=float))
        with ThreadPoolExecutor(max_workers=2) as executor:
            giver_exec = executor.submit(
                robot_2.render_exec,
                is_synchronizer=False,
            )
            receiver_exec = executor.submit(
                robot_1.render_exec,
                is_synchronizer=True,
            )
            giver_exec.result()
            receiver_exec.result()
        robot_1.eef_attach("IRB6620_R1", "Gripper", "Top Sill Plate")
        robot_2.eef_detach("IRB6620_R2", "Gripper", "Top Sill Plate")
        with ThreadPoolExecutor(max_workers=2) as executor:
            giver_home = executor.submit(
                robot_2.move_to_home
            )
            receiver_home = executor.submit(
                robot_1.move_to_home
            )
            giver_home.result()
            receiver_home.result()

        robot_1.plan("tool0", np.array([X + 1.132590, 0.0, H + 0.989360], dtype=float), np.array([0.0, 0.0, 1.0, 0.0], dtype=float))
        robot_1.render_exec()
        robot_1.eef_detach("IRB6620_R1", "tool0", "Top Sill Plate")
        robot_1.move_to_home()

    def hlaf_018_top_sill_plate_nail_or_screw_plate_to_king_studs_and_to_any_top_cripple_stud(self, element_object_name: str, *, W: float, H: float, X: float) -> None:
        """
        Element: Top Sill Plate
        Sub-Step: Nail or screw plate to king studs and to any top cripple studs above
        """
        robot_1 = self.robots["Robot_1"]

        robot_1.plan("tool2", np.array([X + 1.132590, 0.413397 - (W / 2), 0.945460 + (0.300000 * H)], dtype=float), np.array([0.182999, -0.682994, 0.682994, 0.182999], dtype=float))
        robot_1.render_exec()
        robot_1.move_to_home()

    def hlaf_019_top_cripple_stud_position_cripples_at_on_center_spacing_above_opening_betwee(self, element_object_name: str, *, L: float, W: float, H: float, X: float) -> None:
        """
        Element: Top Cripple Stud
        Sub-Step: Position cripples at on-center spacing above opening between header and top plate
        """
        robot_2 = self.robots["Robot_2"]
        robot_1 = self.robots["Robot_1"]

        robot_2.plan('tool0', np.array([6.450100, 0.782470, 0.803000 + (W / 2)], dtype=float), np.array([-0.707107, 0.0, -0.707107, 0.0], dtype=float))
        robot_2.render_exec()
        robot_2.eef_attach('IRB6620_R2', 'tool0', 'Top Cripple Stud')
        robot_2.move_to_home()

        robot_2.plan("tool0", np.array([1.762200 - (H / 2), -0.150000, 1.550000], dtype=float), np.array([0.0, 0.707107, 0.0, 0.707107], dtype=float))
        robot_1.plan("tool0", np.array([1.762200 - (H / 2), -0.150000, 1.550000], dtype=float), np.array([0.0, 0.707107, 0.0, 0.707107], dtype=float))
        with ThreadPoolExecutor(max_workers=2) as executor:
            giver_exec = executor.submit(
                robot_2.render_exec,
                is_synchronizer=False,
            )
            receiver_exec = executor.submit(
                robot_1.render_exec,
                is_synchronizer=True,
            )
            giver_exec.result()
            receiver_exec.result()
        robot_1.eef_attach("IRB6620_R1", "tool0", "Top Cripple Stud")
        robot_2.eef_detach("IRB6620_R2", "tool0", "Top Cripple Stud")
        with ThreadPoolExecutor(max_workers=2) as executor:
            giver_home = executor.submit(
                robot_2.move_to_home
            )
            receiver_home = executor.submit(
                robot_1.move_to_home
            )
            giver_home.result()
            receiver_home.result()

        robot_1.plan("Gripper", np.array([X + (L / 2) + 0.932590, 0.5, H + 0.989360], dtype=float), np.array([0.0, 0.0, -0.707107, -0.707107], dtype=float))
        robot_1.render_exec()
        robot_1.eef_detach("IRB6620_R1", "tool0", "Top Cripple Stud")
        robot_1.move_to_home()

    def hlaf_020_top_cripple_stud_fasten_cripples_through_top_plate_and_header_with_nails_or(self, element_object_name: str, *, H: float) -> None:
        """
        Element: Top Cripple Stud
        Sub-Step: Fasten cripples through top plate and header with nails or screws
        """
        robot_1 = self.robots["Robot_1"]

        robot_1.plan('tool2', np.array([1.100000, 0.500000, 0.895460 + (0.300000 * H)], dtype=float), np.array([0.0, 0.707107, 0.0, 0.707107], dtype=float))
        robot_1.render_exec()
        robot_1.move_to_home()

